[phases.setup]
workingDirectory = "app"
aptPackages = ["python3", "make", "g++", "python3-pip", "build-essential"]

[phases.build]
workingDirectory = "app"
commands = ["npm install", "npm run build:remix"]

[phases.start]
workingDirectory = "app"
commands = ["npm run start"]

[environment]
nodeVersion = "22.11.0"
pythonVersion = "3.11"

[files]
include = ["app/**/*"]
exclude = [".git", "node_modules", "build"]
