[phases.setup]
workingDirectory = "app"
aptPackages = [
  "build-essential",
    "libusb-1.0-0-dev",
    "python3",
    "python3-pip",
    "make",
    "g++"
]

[phases.build]
commands = ["pnpm run build:remix"]

[phases.start]
commands = ["pnpm run start"]

[environment]
nodeVersion = "22.11.0"
pythonVersion = "3.11"
npm_config_fallback_to_build = "true"

[files]
exclude = [".git", "node_modules", "build"]
