[phases.setup]
workingDirectory = "app"
aptPackages = [
  "build-essential", 
  "libusb-1.0-0-dev", 
  "python3", 
  "python3-pip", 
  "make", 
  "g++"]

[environment]
nodeVersion = "22.11.0"
pythonVersion = "3.11"

[files]
include = ["app/**/*"]
exclude = [".git", "node_modules", "build"]
