[phases.setup]
workingDirectory = "app"
aptPackages = ["python3", "make", "g++", "python3-pip", "build-essential"]

[environment]
nodeVersion = "22.11.0"
pythonVersion = "3.11"

[files]
include = ["app/**/*"]
exclude = [".git", "node_modules", "build"]
